spring:
  couchbase:
    env:
      timeouts:
        view: 15000
        query: 15000
    connection-string: couchbase://127.0.0.1
    username: Administrator
    password: password
  data:
    couchbase:
      auto-index: true
